import PptxGenJS from "pptxgenjs";
import { FullPitchDeck } from "./anthropic";

export function generatePptxBuffer(deck: FullPitchDeck): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";
  pptx.author = "Velocity Forge AI";
  pptx.subject = `${deck.companyName} Pitch Deck`;
  pptx.title = `${deck.companyName} — ${deck.tagline}`;

  // Brand colors
  const darkBg = "0F0F23";
  const accentPurple = "A855F7";
  const accentBlue = "3B82F6";
  const lightText = "F9FAFB";
  const mutedText = "9CA3AF";

  for (const slide of deck.slides) {
    const s = pptx.addSlide();

    // Dark gradient background
    s.background = { color: darkBg };

    // Accent bar at top
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 0.06,
      fill: { type: "solid", color: accentPurple },
    });

    if (slide.slideNumber === 1) {
      // Title slide - special layout
      s.addText(deck.companyName, {
        x: 0.8,
        y: 1.5,
        w: 8.4,
        h: 1.5,
        fontSize: 44,
        bold: true,
        color: lightText,
        fontFace: "Arial",
      });

      s.addText(deck.tagline, {
        x: 0.8,
        y: 3.0,
        w: 8.4,
        h: 0.8,
        fontSize: 22,
        color: accentPurple,
        fontFace: "Arial",
      });

      if (slide.bullets && slide.bullets.length > 0) {
        s.addText(
          slide.bullets.map((b) => ({
            text: b,
            options: { bullet: true, color: mutedText, fontSize: 14, breakLine: true },
          })),
          {
            x: 0.8,
            y: 4.0,
            w: 8.4,
            h: 1.5,
            fontFace: "Arial",
          }
        );
      }

      // Branding footer
      s.addText("Generated by Velocity Forge AI", {
        x: 0.8,
        y: 6.8,
        w: 4,
        h: 0.3,
        fontSize: 9,
        color: "4B5563",
        fontFace: "Arial",
      });
    } else if (slide.slideNumber === 10) {
      // Closing slide - CTA style
      s.addText(slide.title, {
        x: 0.8,
        y: 0.5,
        w: 8.4,
        h: 0.8,
        fontSize: 36,
        bold: true,
        color: lightText,
        fontFace: "Arial",
      });

      if (slide.subtitle) {
        s.addText(slide.subtitle, {
          x: 0.8,
          y: 1.3,
          w: 8.4,
          h: 0.5,
          fontSize: 18,
          color: accentPurple,
          fontFace: "Arial",
        });
      }

      if (slide.bullets && slide.bullets.length > 0) {
        s.addText(
          slide.bullets.map((b) => ({
            text: b,
            options: { bullet: true, color: lightText, fontSize: 16, breakLine: true, paraSpaceAfter: 8 },
          })),
          {
            x: 0.8,
            y: 2.2,
            w: 8.4,
            h: 3.5,
            fontFace: "Arial",
            valign: "top",
          }
        );
      }

      // CTA box
      s.addShape(pptx.ShapeType.roundRect, {
        x: 2.5,
        y: 5.8,
        w: 5,
        h: 0.8,
        fill: { type: "solid", color: accentPurple },
        rectRadius: 0.1,
      });
      s.addText("Let's Build the Future Together", {
        x: 2.5,
        y: 5.8,
        w: 5,
        h: 0.8,
        fontSize: 18,
        bold: true,
        color: lightText,
        fontFace: "Arial",
        align: "center",
        valign: "middle",
      });
    } else {
      // Standard content slides
      s.addText(slide.title, {
        x: 0.8,
        y: 0.4,
        w: 8.4,
        h: 0.8,
        fontSize: 32,
        bold: true,
        color: lightText,
        fontFace: "Arial",
      });

      if (slide.subtitle) {
        s.addText(slide.subtitle, {
          x: 0.8,
          y: 1.15,
          w: 8.4,
          h: 0.45,
          fontSize: 16,
          color: accentBlue,
          fontFace: "Arial",
        });
      }

      // Divider line
      s.addShape(pptx.ShapeType.line, {
        x: 0.8,
        y: 1.7,
        w: 8.4,
        h: 0,
        line: { color: "374151", width: 1 },
      });

      if (slide.bullets && slide.bullets.length > 0) {
        s.addText(
          slide.bullets.map((b) => ({
            text: b,
            options: {
              bullet: { type: "bullet", style: "•" },
              color: lightText,
              fontSize: 18,
              breakLine: true,
              paraSpaceAfter: 12,
            },
          })),
          {
            x: 0.8,
            y: 2.0,
            w: 8.4,
            h: 4.2,
            fontFace: "Arial",
            valign: "top",
          }
        );
      }

      // Slide number
      s.addText(`${slide.slideNumber} / ${deck.slides.length}`, {
        x: 8.5,
        y: 6.8,
        w: 1,
        h: 0.3,
        fontSize: 9,
        color: "4B5563",
        fontFace: "Arial",
        align: "right",
      });
    }

    // Add speaker notes
    if (slide.speakerNotes) {
      s.addNotes(slide.speakerNotes);
    }
  }

  return pptx.write({ outputType: "nodebuffer" }) as Promise<Buffer>;
}
